[package]
name = "gdax_daemon"
version = "0.1.0"
authors = ["wclaeder <codylaeder@gmail.com>"]

[dependencies]
websocket = "0.17.1"
unix_socket = "0.5.0"
openssl = "0.7.6"
regex = "0.1"
lazy_static = "0.2.1"
